FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
# Install dependencies
RUN apt update && apt upgrade -y \
&& apt install -y \
    python3 \
    python3-pip \
    python-is-python3 \
    python3-dev \
    python3-venv \
    tmux \
    supervisor \
    curl \
    git \
    vim \
&& pip3 install flask \
    flask-restx \
    paho-mqtt \
    pymysql \
    cryptography

CMD ["python3", "main.py"]