version: '3.8'
services:
  app:
    privileged: true
    volumes:
      - ../App:/home
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
    build:
      context: .
      dockerfile: ./dockerFile/app/Dockerfile.app
    tty: true
    stdin_open: true
  server:
    privileged: true
    volumes:
      - ../Server:/home
    network_mode: host
    build:
      context: .
      dockerfile: ./dockerFile/server/Dockerfile.server
    working_dir: /home
    tty: true
    stdin_open: true
